<?php
// $Id$

/**
 * Implementation of hook_form_alter().
 */
function groups_breadcrumb_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'comment_form' && arg(0) == 'comment') {
    $node = node_load($form['nid']['#value']);
    drupal_set_breadcrumb(array(
      l(t('Home'), NULL),
      l(t('Groups'), 'groups'),
      l($node->title, 'node/'. $node->nid)
    ));
  }
}


/**
 * Implementation of hook_nodeapi().
 */
function groups_breadcrumb_nodeapi(&$node, $op, $teaser, $page) {
  if (arg(0) == 'node' && $op == 'alter' && $node->nid == arg(1)) {
    if (og_is_group_post_type($node->type)) {
      reset($node->og_groups);
      $group_nid = current($node->og_groups);
      $group_title = $node->og_groups_both[$group_nid];

      if ($group_lang = _group_breadcrumb_get_translations($group_nid)) {
        $group_title = $group_lang->title;
        $group_nid = $group_lang->nid;
      }

      drupal_set_breadcrumb(array(
        l(t('Home'), NULL),
        l(t('Groups'), 'groups'),
        l($group_title, 'node/' . $group_nid),
        drupal_get_title(),
      ));
    }
    elseif (og_is_group_type($node->type)) {
      drupal_set_breadcrumb(array(
        l(t('Home'), NULL),
        l(t('Groups'), 'groups'),
        drupal_get_title(),
      ));
    }
    else {
      if ($node->type == 'events') {
        drupal_set_breadcrumb(array(
          l(t('Home'), NULL),
          l(t('Events'), 'events'),
          drupal_get_title(),
        ));
      }
      if ($node->type == 'helper') {
        drupal_set_breadcrumb(array(
          l(t('Home'), NULL),
          l(t('Questions/Answers'), 'question'),
          drupal_get_title(),
        ));
      }
    }
  }
}


/**
 * Addition function:
 *
 * Get translated Group.
 */
function _group_breadcrumb_get_translations($gid) {
  global $language;
  $group = FALSE;
  if ($translation = translation_node_get_translations($gid)) {
    if (isset($translation[$language->language])) {
      $group = $translation[$language->language];
    }
  }
  else {
    if ($group_node = node_load($gid)) {
      if ($group_node->tnid) {
        $translation = translation_node_get_translations($group_node->tnid);
        if (isset($translation[$language->language])) {
          $group = $translation[$language->language];
        }
      }
    }
  }
  return $group;
}
