<?php
/**
 * files module idevels_send_email.
 */

/**
 * Implements hook_cron().
 **/
function idevels_send_mail_cron() {
  $date = new DateTime();
  $timenow = strtotime('-1 day', date_timestamp_get($date));
  $events = db_query("SELECT * FROM {idevels_send_mail}");
  while ($event = db_fetch_object($events)) {
    if ($timenow >= $event->timestamp) {
      $node = node_load(array("nid" => $event->nid));
      $user = user_load(array('uid' => $event->uid));
      $message = array(
        'to' => $user->mail,
        'subject' => $node->title,
        'body' => t('test body'),
        'headers' => array(
          'Reply-To' => variable_get('site_name', ''),
          'MIME-Version' => '1.0',
          'Content-Type' => 'text/plain; charset=UTF-8; format=flowed; delsp=yes',
          'Content-Transfer-Encoding' => '8Bit',
          'From' => variable_get('site_name', ''),
          'X-Mailer' => 'Drupal',
        ),
      );
      job_queue_add('drupal_mail_send', 'Send email for user=>' . $user->name . 'for event' . $node->title, array($message), '', TRUE);
    }
  }
  db_query("Delete FROM {idevels_send_mail} where timestamp<=%d", array($timenow));
}

/**
 * Implements hook_flag().
 **/
function idevels_send_mail_flag($op, $flag, $content_id, $account, $fcid) {
  $uid = $account->uid;
  if ($op == 'unflag') {
    db_query('Delete from {idevels_send_mail}  WHERE nid=%s and uid=%s', array(
      $content_id,
      $uid,
    ));
  }
  if ($op == 'flag' and in_array('events', $flag->types)) {
    $date = new DateTime();
    $timestamp = date_timestamp_get($date);
    db_query('INSERT INTO {idevels_send_mail}(id, uid, nid, timestamp) VALUES (null, %s, %s, %s)', array(
      $uid,
      $content_id,
      $timestamp,
    ));
  }
}

/**
 * Implements hook_job_queue_functions().
 */
function idevels_send_mail_job_queue_functions() {
  $functions['drupal_send_mail'] = array(
    'title' => t('Idevels send mail'),
  );

  return $functions;
}
